# Generated by Django 5.2.5 on 2025-09-28 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('nisn', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('student_class', models.CharField(max_length=10)),
                ('entry_year', models.IntegerField(default=2025)),
                ('test_status', models.CharField(choices=[('pending', 'Belum Tes'), ('in_progress', 'Sedang Tes'), ('completed', 'Selesai')], default='pending', max_length=15)),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('parent_phone', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'ordering': ['student_class', 'name'],
                'indexes': [models.Index(fields=['nisn'], name='students_st_nisn_b9825c_idx'), models.Index(fields=['student_class'], name='students_st_student_8b8308_idx'), models.Index(fields=['test_status'], name='students_st_test_st_8a78e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis', models.CharField(choices=[('akademik', 'Prestasi Akademik'), ('olahraga', 'Prestasi Olahraga'), ('seni', 'Prestasi Seni'), ('organisasi', 'Prestasi Organisasi'), ('teknologi', 'Prestasi Teknologi'), ('keagamaan', 'Prestasi Keagamaan')], max_length=20)),
                ('nama', models.CharField(max_length=200)),
                ('tingkat', models.CharField(choices=[('sekolah', 'Tingkat Sekolah'), ('kecamatan', 'Tingkat Kecamatan'), ('kabupaten', 'Tingkat Kabupaten'), ('provinsi', 'Tingkat Provinsi'), ('nasional', 'Tingkat Nasional'), ('internasional', 'Tingkat Internasional')], max_length=20)),
                ('peringkat', models.CharField(max_length=20)),
                ('tahun', models.IntegerField()),
                ('keterangan', models.TextField(blank=True)),
                ('sertifikat', models.FileField(blank=True, upload_to='sertifikat_prestasi/')),
                ('bonus_score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
