# Generated by Django 5.2.5 on 2025-09-28 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestasi',
            options={'ordering': ['-tahun', 'tingkat', 'nama'], 'verbose_name': 'Prestasi', 'verbose_name_plural': 'Prestasi'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_class', 'name'], 'verbose_name': 'Siswa', 'verbose_name_plural': 'Siswa'},
        ),
        migrations.AddField(
            model_name='student',
            name='generated_password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
