# Generated by Django 5.2.5 on 2025-09-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_prestasi_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMIBResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rankings', models.JSONField(default=dict)),
                ('original_scores', models.JSONField(default=dict)),
                ('final_scores', models.JSONField(default=dict)),
                ('top_interests', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField()),
                ('primary_interest', models.CharField(blank=True, max_length=20)),
                ('secondary_interest', models.CharField(blank=True, max_length=20)),
                ('tertiary_interest', models.CharField(blank=True, max_length=20)),
                ('career_recommendations', models.JSONField(default=list)),
                ('study_recommendations', models.JSONField(default=list)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rmib_result', to='students.student')),
            ],
            options={
                'verbose_name': 'Hasil RMIB',
                'verbose_name_plural': 'Hasil RMIB',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
