# Generated by Django 4.2 on 2025-10-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rmibresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmibresult',
            name='career_recommendations',
        ),
        migrations.RemoveField(
            model_name='rmibresult',
            name='final_scores',
        ),
        migrations.RemoveField(
            model_name='rmibresult',
            name='original_scores',
        ),
        migrations.RemoveField(
            model_name='rmibresult',
            name='rankings',
        ),
        migrations.RemoveField(
            model_name='rmibresult',
            name='study_recommendations',
        ),
        migrations.RemoveField(
            model_name='rmibresult',
            name='top_interests',
        ),
        migrations.AddField(
            model_name='rmibresult',
            name='category_scores',
            field=models.JSONField(default=dict, help_text='Score per kategori (level × 5)'),
        ),
        migrations.AddField(
            model_name='rmibresult',
            name='levels',
            field=models.JSONField(default=dict, help_text='Levels untuk setiap kategori (1-12)'),
        ),
        migrations.AddField(
            model_name='rmibresult',
            name='primary_level',
            field=models.IntegerField(default=0, help_text='Level dari primary interest'),
        ),
        migrations.AddField(
            model_name='rmibresult',
            name='secondary_level',
            field=models.IntegerField(default=0, help_text='Level dari secondary interest'),
        ),
        migrations.AddField(
            model_name='rmibresult',
            name='tertiary_level',
            field=models.IntegerField(default=0, help_text='Level dari tertiary interest'),
        ),
        migrations.AddField(
            model_name='rmibresult',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Total score dari semua kategori'),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='primary_interest',
            field=models.CharField(blank=True, help_text='Kategori dengan level tertinggi', max_length=20),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='secondary_interest',
            field=models.CharField(blank=True, help_text='Kategori dengan level tertinggi kedua', max_length=20),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='submitted_at',
            field=models.DateTimeField(help_text='Waktu tes diselesaikan'),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='tertiary_interest',
            field=models.CharField(blank=True, help_text='Kategori dengan level tertinggi ketiga', max_length=20),
        ),
    ]
