# Generated by Django 4.2 on 2025-10-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_rmibresult_career_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmibresult',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Waktu terakhir diedit', null=True),
        ),
        migrations.AddField(
            model_name='rmibresult',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('edited', 'Diedit')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='primary_interest',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='primary_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='secondary_interest',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='secondary_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='tertiary_interest',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rmibresult',
            name='tertiary_level',
            field=models.IntegerField(default=0),
        ),
    ]
