# Generated by Django 4.2 on 2025-11-01 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_rmibresult_edited_at_rmibresult_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Kode unik, misal: MAT-001', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Bidang Prestasi, misal: Matematika', max_length=200)),
                ('category', models.CharField(choices=[('akademik', 'Akademik'), ('non_akademik', 'Non-Akademik')], max_length=20)),
                ('sub_category', models.CharField(help_text='Misal: Sains Eksak', max_length=100)),
                ('rmib_primary', models.CharField(help_text='Kategori RMIB Primer, misal: scientific', max_length=20)),
                ('rmib_secondary', models.CharField(blank=True, help_text='Kategori RMIB Sekunder', max_length=50)),
                ('example_competitions', models.TextField(help_text='Contoh lomba/kegiatan')),
                ('available_levels', models.CharField(default='sekolah,kecamatan,kabupaten,provinsi,nasional,internasional', max_length=100)),
                ('description', models.TextField(help_text='Keterangan/penjelasan')),
                ('icon', models.CharField(default='fas fa-trophy', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jenis Prestasi',
                'verbose_name_plural': 'Jenis Prestasi',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('sekolah', 'Sekolah'), ('kecamatan', 'Kecamatan'), ('kabupaten', 'Kabupaten/Kota'), ('provinsi', 'Provinsi'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], max_length=20)),
                ('rank', models.CharField(choices=[('juara_1', 'Juara 1'), ('juara_2', 'Juara 2'), ('juara_3', 'Juara 3'), ('harapan', 'Juara Harapan/Finalis')], max_length=20)),
                ('year', models.IntegerField(help_text='Tahun prestasi diraih')),
                ('points', models.IntegerField(default=0, help_text='Poin prestasi berdasarkan level & rank')),
                ('rmib_contributions', models.JSONField(default=dict, help_text="Kontribusi ke kategori RMIB, misal: {'scientific': 80, 'computational': 40}")),
                ('certificate', models.FileField(blank=True, help_text='Upload sertifikat/bukti', upload_to='achievements/%Y/')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan')),
                ('is_verified', models.BooleanField(default=False, help_text='Sudah diverifikasi oleh guru/admin')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('achievement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_achievements', to='students.achievementtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestasi Siswa',
                'verbose_name_plural': 'Prestasi Siswa',
                'ordering': ['-year', '-points', 'achievement_type__name'],
            },
        ),
        migrations.DeleteModel(
            name='Prestasi',
        ),
        migrations.AddIndex(
            model_name='studentachievement',
            index=models.Index(fields=['student', '-year'], name='students_st_student_cb9007_idx'),
        ),
        migrations.AddIndex(
            model_name='studentachievement',
            index=models.Index(fields=['achievement_type', 'level'], name='students_st_achieve_adad99_idx'),
        ),
        migrations.AddIndex(
            model_name='studentachievement',
            index=models.Index(fields=['is_verified'], name='students_st_is_veri_717c99_idx'),
        ),
    ]
