# Generated by Django 4.2 on 2025-11-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_achievementtype_studentachievement_delete_prestasi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementtype',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': 'Achievement Types'},
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='available_levels',
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='example_competitions',
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='category',
            field=models.CharField(choices=[('academic', '🎓 Akademik'), ('non_academic', '🎨 Non-Akademik'), ('other', 'Lainnya')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='rmib_primary',
            field=models.CharField(blank=True, choices=[('outdoor', 'Outdoor'), ('mechanical', 'Mechanical'), ('computational', 'Computational'), ('scientific', 'Scientific'), ('personal_contact', 'Personal Contact'), ('aesthetic', 'Aesthetic'), ('literary', 'Literary'), ('musical', 'Musical'), ('social_service', 'Social Service'), ('clerical', 'Clerical'), ('practical', 'Practical'), ('medical', 'Medical')], help_text='Kategori RMIB utama', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='rmib_secondary',
            field=models.CharField(blank=True, choices=[('outdoor', 'Outdoor'), ('mechanical', 'Mechanical'), ('computational', 'Computational'), ('scientific', 'Scientific'), ('personal_contact', 'Personal Contact'), ('aesthetic', 'Aesthetic'), ('literary', 'Literary'), ('musical', 'Musical'), ('social_service', 'Social Service'), ('clerical', 'Clerical'), ('practical', 'Practical'), ('medical', 'Medical')], help_text='Kategori RMIB sekunder', max_length=50, null=True),
        ),
    ]
