# Generated by Django 4.2 on 2025-11-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_achievementtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('certificate', 'Certificate'), ('summary', 'Summary Sheet'), ('parent', 'Parent Report')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('downloaded', 'Downloaded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='students.student')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
