# Generated by Django 4.2 on 2025-11-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_certificaterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificaterequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Certificate Request', 'verbose_name_plural': 'Certificate Requests'},
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='file_size',
            field=models.IntegerField(default=0, help_text='Ukuran file dalam bytes'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan khusus dari admin'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - Menunggu Generate'), ('generated', 'Generated - Siap Download'), ('downloaded', 'Downloaded - Sudah Diunduh'), ('expired', 'Expired - Kadaluarsa')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='template_type',
            field=models.CharField(choices=[('certificate', 'Sertifikat Hasil RMIB'), ('summary', 'Lembar Ringkasan Minat'), ('parent', 'Laporan Orang Tua')], max_length=20),
        ),
    ]
