# Generated by Django 5.2.5 on 2025-09-28 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMIBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('career_fields', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RMIBScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outdoor', models.IntegerField(default=0, verbose_name='Outdoor (OUT)')),
                ('mechanical', models.IntegerField(default=0, verbose_name='Mechanical (ME)')),
                ('computational', models.IntegerField(default=0, verbose_name='Computational (COMP)')),
                ('scientific', models.IntegerField(default=0, verbose_name='Scientific (SCI)')),
                ('personal', models.IntegerField(default=0, verbose_name='Personal (PERS)')),
                ('aesthetic', models.IntegerField(default=0, verbose_name='Aesthetic (AEST)')),
                ('literary', models.IntegerField(default=0, verbose_name='Literary (LIT)')),
                ('musical', models.IntegerField(default=0, verbose_name='Musical (MUS)')),
                ('social_service', models.IntegerField(default=0, verbose_name='Social Service (SS)')),
                ('clerical', models.IntegerField(default=0, verbose_name='Clerical (CLER)')),
                ('practical', models.IntegerField(default=0, verbose_name='Practical (PRAC)')),
                ('medical', models.IntegerField(default=0, verbose_name='Medical (MED)')),
                ('test_duration', models.DurationField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=150)),
                ('completed_questions', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rmib_score', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
