# Generated by Django 5.2.5 on 2025-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=10)),
                ('total_students', models.IntegerField(default=0)),
                ('completed_tests', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('report_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, upload_to='class_reports/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Laporan Bulanan'), ('semester', 'Laporan Semester'), ('yearly', 'Laporan Tahunan')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_students', models.IntegerField(default=0)),
                ('completed_tests', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, upload_to='system_reports/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
